### ISSUE TITLE
作业一求助

### ISSUE THREAD

**Issue by ghost** [JPLAY0/CS231nAssignment#11]
您好：
我刚开始学cs231n课程，请问作业一里的代码“from cs231n.data_utils import load_CIFAR10” 中的“cs231n.data_utils”是什么呀？还有文件夹cs231n里是什么，和外面的ipynby文件有什么关系呀？
谢谢！

**Comment by JPLAY0** [comment]
建议你系统地学下python的模块这块的知识再来做这个作业。

**Comment by ghost** [comment]
具体问题是这个错误：“cannot import name 'imread' from 'scipy.misc'”,现在已经解决了。
